server:
  port: 9292

spring:
  application:
    name: product-query-service
  cloud:
    compatibility-verifier:
      enabled: false

  datasource:
    continue-on-error: true
    initialize: true
    password: password
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  zipkin:
    base-url: http://localhost:9411/
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  health:
    bulkhead:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always

  observations:
    key-values:
      application: product-query-service

logging:
  level:
    root: INFO

#  pattern:
#    correlation: [${spring:application:name:},%X{traceId:-},%X{spanId:-}]

resilience4j:
  bulkhead:
    configs:
      default:
        maxConcurrentCalls: 5
        maxWaitDuration: 0
    instances:
      ratingServiceBulkhead:
        maxConcurrentCalls: 5
